### ISSUE TITLE
doesn't comply with react-hooks/exhaustive-deps eslint rule

### ISSUE THREAD

**Issue by saltycrane** [the-road-to-learn-react/react-hooks-introduction#6]
Thanks for [your blog post on data fetching with React Hooks](https://www.robinwieruch.de/react-hooks-fetch-data/). I'm learning React Hooks and found it helpful.

Dan Abramov recently released a [react-hooks/exhaustive-deps eslint rule](https://github.com/facebook/react/issues/14920). So I [added `eslint-plugin-react-hooks` to a fork of this repo](https://github.com/saltycrane/react-hooks-introduction/commit/7a3d59386811cd40e617088e4e6e1b69a37a1f0f) and got the following errors:

```
$ npm run -s eslint

/opt/gh/react-hooks-introduction/src/customHook-example/index.js
  22:6  warning  React Hook useEffect has missing dependencies: 'onOffline' and 'onOnline'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

/opt/gh/react-hooks-introduction/src/useDataApiHook-example/index.js
  29:5  warning  React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

✖ 2 problems (0 errors, 2 warnings)
  0 errors and 2 warnings potentially fixable with the `--fix` option.
```

I have come up with solutions in my own code, but am curious how others such as yourself would solve them.

**Comment by rwieruch** [comment]
Do these changes make sense? https://github.com/the-road-to-learn-react/react-hooks-introduction/pull/7 The first commit is used to comply with the ESLint rules.

**Comment by saltycrane** [comment]
Yes, thanks for the update!
